/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import entidades.*;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistencia.*;

/**
 *
 * @author lucio
 */
public class VistaCargarNota extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo = new DefaultTableModel ();
    AlumnoData alum = new AlumnoData ();
    InscripcionData inscr = new InscripcionData ();
    MateriaData mat = new MateriaData ();

    /**
     * Creates new form VistaCargarNota
     */
    public VistaCargarNota() {
        initComponents();
        cargarAlumno ();
        cabecera ();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfNota = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jcbAlumno = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtMateria = new javax.swing.JTable();
        jbGuardar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cargar Notas");

        jLabel5.setText("Ingrese Nota: ");

        jLabel6.setText("Alumno: ");

        jcbAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAlumnoActionPerformed(evt);
            }
        });

        jtMateria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtMateria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtMateriaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtMateria);

        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfNota)
                    .addComponent(jcbAlumno, 0, 229, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(jbGuardar)
                .addGap(79, 79, 79))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(271, 271, 271))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbSalir)
                        .addGap(81, 81, 81))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jcbAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbGuardar))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbSalir)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        dispose ();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jcbAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAlumnoActionPerformed
        // TODO add your handling code here:
        cargarMateriaXAlumno();
    }//GEN-LAST:event_jcbAlumnoActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        // TODO add your handling code here:
        guardarNota();
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jtMateriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtMateriaMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jtMateriaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<Object> jcbAlumno;
    private javax.swing.JTable jtMateria;
    private javax.swing.JTextField jtfNota;
    // End of variables declaration//GEN-END:variables

    private void cabecera (){
        
        modelo.addColumn("Id Materia");
        modelo.addColumn("Materia");
        modelo.addColumn("Año");
        modelo.addColumn("Nota");
        jtMateria.setModel(modelo);
        jtMateria.setDefaultEditor(Object.class, null);

    }

    private void cargarAlumno(){
        
       jcbAlumno.removeAllItems();
       List <Alumno> alumnos =  alum.listarAlumnos();
       
        for (Alumno a : alumnos) {
            
            jcbAlumno.addItem(a);
        }
    }
    
    private void cargarMateriaXAlumno (){
        
        limpiarTabla ();
        
        Alumno alumno = (Alumno) jcbAlumno.getSelectedItem();
        
        if (alumno != null) {
            
            List <Inscripcion> inscrip = inscr.ObtenerInscripcionesPorAlumno(alumno.getId_alunmo());
            
            for (Inscripcion i : inscrip) {
                                
                modelo.addRow (new Object []{
                    
                    i.getMateria().getIdMateria(),
                    i.getMateria().getNombre(),
                    i.getMateria().getAnio(),
                    i.getNota()
                });
            }
            
        }
    }
    
    private void guardarNota (){
        
        int fila = jtMateria.getSelectedRow();
        
        int nota = Integer.parseInt(jtfNota.getText()) ;
        
        if (fila != -1) {
            
            if (nota >= 0 && nota <= 10) {
                
            
                try{
                
                    Alumno alumno = (Alumno) jcbAlumno.getSelectedItem();
            
                    int idMateria = (int) jtMateria.getValueAt(fila, 0);
                
                
                    inscr.actualizarNota(alumno.getId_alunmo(), idMateria, nota);
                
                    modelo.setValueAt(nota, fila, 3);
                
                    JOptionPane.showMessageDialog(this, "Nota Agregada con exito.");
                
                    jtfNota.setText("");
                
                }catch (NumberFormatException e){
                
                    JOptionPane.showMessageDialog(this, "Ingrese una nota valida (Numero Entero)");
                }
            } else {
                
                JOptionPane.showMessageDialog(this, "Ingrese una Nota correcta. ");
            }
        } else {
            
            JOptionPane.showMessageDialog(this, "Seleccione una materia de la tabla.");
        }
    }

    
    private void limpiarTabla (){
        
        modelo.setRowCount(0);
    }
}
